# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # usr_demo:pwd_demo@mongo:27017/my_employees
    - name: MongoDB Action
      # You may pin to the exact commit or the version.
      # uses: SusanDoggie/mongodb-action@a150cf7ccd58d490da82ffb225a43abcc7a9d347
      uses: SusanDoggie/mongodb-action@0.0.1
      with:
        # Docker network to use (default "bridge")
        network: bridge # optional, default is bridge
        # MongoDB version to use (default "latest")
        version: 4.4 # optional, default is latest
        # MongoDB version to use (default "mongo")
        host: mongo # optional, default is mongo
        # MongoDB port to use (default 27017)
        port: 27017 # optional, default is 27017
        # MongoDB root username (default: none)
        username: usr_demo # optional, default is 
        # MongoDB root password (default: none)
        password: pwd_demo # optional, default is 
        # MongoDB db to create (default: none)
        database: my_employees # optional, default is 

    - run: npm ci

    - name: Run Test Script
      run: npm test
      env: 
        PORT: 5000
        # DB_URL: ${{ secrets.DB_URL }}
        # TEST_DB_URL: ${{ secrets.DB_URL }}
        DB_URL: usr_demo:pwd_demo@mongo:27017/my_employees
        TEST_DB_URL: usr_demo:pwd_demo@mongo:27017/my_employees
