# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Start MongoDB As Docker
      # You may pin to the exact commit or the version.
      # uses: wbari/start-mongoDB@eb9a4b97a1a252bbaebb98f5fc088ca1f972905a
      uses: wbari/start-mongoDB@v0.2
      with:
        # MongoDB Version
        mongoDBVersion: 4.2 # default is 3.6

    - run: npm ci
    
    - name: Run Test Script
      run: npm test
      env: 
        PORT: 5000
        # DB_URL: ${{ secrets.DB_URL }}
        # TEST_DB_URL: ${{ secrets.DB_URL }}
        TEST_DB_URL: localhost:27017/my_employees
